# Generated by Django 4.1.3 on 2023-04-20 22:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("books", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="user",
            field=models.CharField(max_length=50, null=True),
        ),
    ]
